package generator;

public class BashRunnerGenerator {
	private static write(outputDirectory, projectName) {
		def runMultiBashFile = new File("$outputDirectory/run.sh")
		
		runMultiBashFile.write("""#!/bin/bash

# Generated by BashRunnerGenerator

declare -r script_dir=`cd "\$( dirname "\$0" )" && pwd`
cd \$script_dir

processes_count=\$1

if [ -z "\$processes_count" ]; then
	processes_count="1"
fi

interval_seconds=\$2

if [ -z "\$interval_seconds" ]; then
	interval_seconds="1"
fi

deployments_count=\$3

if [ -z "\$deployments_count" ]; then
	deployments_count="5"
fi

servers_count=\$4

if [ -z "\$servers_count" ]; then
	servers_count="1"
fi

apps_count=\$5

if [ -z "\$apps_count" ]; then
	apps_count="1"
fi

host_name=`hostname`

for ((i=1;i<=\$processes_count;i++)); do
	deploymentName=\$((\$i%\$deployments_count))
	deploymentName="$projectName-deployment-\$deploymentName-\$host_name"
	
	serverName=\$((\$i%\$servers_count))
	serverName="$projectName-server-\$serverName-\$host_name"
	
	appName=\$((\$i%\$apps_count))
	appName="$projectName-app-\$appName-\$host_name"
	
	echo "Running agent number \$i"
	date
	echo java -Dtakipi.server.name="\$serverName" -Dtakipi.name="\$appName" -Dtakipi.deployment.name="\$deploymentName" \
			-Xmx10m -Xms10m -cp \$script_dir/build/libs/${projectName}.jar helpers.Main \
			-ec 1440 -im 60000 -rc 365 -wm 0 -st -hs -sp -fc 10 -aa "$projectName-\$deploymentName"
	echo ""
	
	nohup java -Dtakipi.server.name="\$serverName" -Dtakipi.name="\$appName" -Dtakipi.deployment.name="\$deploymentName" \
		 -Xmx10m -Xms10m -cp \$script_dir/build/libs/${projectName}.jar helpers.Main \
		-ec 1440 -im 60000 -rc 365 -wm 0 -st -hs -sp -fc 10 -aa "\$deploymentName" &
			
	sleep \$interval_seconds
done

""")
		
		Utils.ant.chmod(file:"$runMultiBashFile", perm:"+x")
	}
}