package generator;

public class GradleGenerator
{
	private static write(outputDirectory, subProjects, mainClass)
	{
		def settingsGradleFile = new File("$outputDirectory/build.gradle")

		def subProjectsDeps = subProjects.collect({ "project(':$it')" }).join(",\n\t")

		settingsGradleFile.write(""" // Generated by App Generator
apply plugin: 'java'

project.ext.set(\"mainClass\", \"$mainClass\")

dependencies
{
    compile $subProjectsDeps
}
""")
	}
}
